const INITIAL_CATEGORY_LIMIT = 9;
const PAGINATION_TRANSFORM_VALUE = 453;
const INITIAL_PAGINATION_MORE_COUNT = 5;
const INITIAL_PAGINATION_ACTIVE_PAGE = 0;
const INITIAL_PAGINATION_DATA_LENGTH = 30;
const INITIAL_SUB_CATEGORY_TRANSFORM = 125;
const INITIAL_PAGINATION_ROWS_PER_PAGE = 15;
const PAGINATION_SMALL_TRANSFORM_VALUE = 227;
const INITIAL_PAGINATION_RANGE_DISPLAYED = 2;
const INITIAL_PAGINATION_MARGIN_DISPLAYED = 1;
const INITIAL_SEARCH_PAGINATION_ROWS_PER_PAGE = 12;

const PaginationConstant = {
  INITIAL_CATEGORY_LIMIT,
  PAGINATION_TRANSFORM_VALUE,
  INITIAL_PAGINATION_MORE_COUNT,
  INITIAL_PAGINATION_DATA_LENGTH,
  INITIAL_SUB_CATEGORY_TRANSFORM,
  INITIAL_PAGINATION_ACTIVE_PAGE,
  INITIAL_PAGINATION_ROWS_PER_PAGE,
  PAGINATION_SMALL_TRANSFORM_VALUE,
  INITIAL_PAGINATION_RANGE_DISPLAYED,
  INITIAL_PAGINATION_MARGIN_DISPLAYED,
  INITIAL_SEARCH_PAGINATION_ROWS_PER_PAGE,
};

export default PaginationConstant;
